### PR TITLE
docs: Add org README

### PR DESCRIPTION
**Pull request by jodh-intel**
Add an organisation level README to welcome visitors to the project
(rather than just the GitHub default, which shows a bunch of repo links).

Fixes: #38.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
The content of the README on this PR is pretty much the same as https://github.com/kata-containers/kata-containers/blob/main/README.md so once this lands, we might want to re-think the README for the main repo.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

What's the best way to keep this and kata-containers repo's README in sync?

**Comment by jodh-intel** [comment]
@fidencio - good question. I was thinking either something like `git clone + cron` or maybe better would be a periodic GitHub action to check all docs in all repos.

**Review by fgiudici — APPROVED** [review]
LGTM, thanks @jodh-intel !

**Comment by jodh-intel** [comment]
Nice - it's "live": https://github.com/kata-containers.

**Pull request merged**
